feat: document use of SecCollectionTimeout
coreruleset/documentation pull request #103
Opened 2023-10-03 05:14 UTC by theseion

2023-10-03 16:04 UTC, dune73 requested changes

2023-10-03 16:04 UTC, dune73 commented on content/development/plugin_writing.md
> +CRS does not set change the default value (`3600`) for the ModSecurity `SecCollectionTimeout` directive. Plugin authors must instruct users to set the directive to an appropriate value if the plugin
The "not set change" is probably a typo. Other than that I think this is good to go.

2023-10-21 08:00 UTC, theseion commented
ping @RedXanadu

2023-11-09 15:31 UTC, RedXanadu requested changes

2023-11-09 15:33 UTC, RedXanadu commented
So, I did not press the correct button to publish the change request… Thank you @theseion!

2023-11-09 16:05 UTC, RedXanadu approved these changes
Awesome, thank you!

2023-11-09 16:09 UTC, dune73 approved these changes

2023-11-09 16:09 UTC, RedXanadu commented
Merging now.

2023-11-09 16:09 UTC, merged