feat(description): add files description in yaml
coreruleset/documentation pull request #50
Opened 2022-05-15 12:41 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Generate file description based on yaml content, not in the markdown file. Played with the idea of adding a general comment to the rules file itself, so it is even easier to maintain. But then I've failed to easily parse that from hugo. So here is my second best approach.

Now we need to add the relevant information on the yaml file only!

2022-05-15 14:16 UTC, airween commented on data/filesdescription.yaml
> +"3":
Is this the version number? If yes, will it enough to represent the whole versioning of rule set?

2022-05-15 14:23 UTC, fzipi commented on data/filesdescription.yaml
> +"3":
It is just a key. We can use more granular if things change in between minor versions.

2022-05-29 13:04 UTC, fzipi commented
@RedXanadu @dune73 What do you think about this approach?

2022-05-29 13:07 UTC, theseion commented
Neat!

2022-05-29 16:08 UTC, RedXanadu commented
Sorry @fzipi, I'll admit, I had a quick look when you submitted this the other week and I didn't understand it. I haven't had time to properly look into it yet. Apologies.

2022-05-30 07:23 UTC, dune73 commented
I see more or less what you are doing here @fzipi. But I do not yet understand the motivation. Could you explain why we need this to be machine readable?

2022-05-30 13:48 UTC, fzipi commented
To me, it's easier to maintain in a centralized place. Having multiple major versions might imply a headache on copy and pasting different files. Keeping the format also is a pain. This way you just write in one file and forget about the format.

Ideally, we could write the comment in the `.conf` file and parse it automagically to generate this content. But there is no easy way to do that.

2024-02-12 13:01 UTC, fzipi commented
Any other comments here?

2024-02-12 17:59 UTC, theseion requested changes

2024-02-12 17:59 UTC, theseion commented on data/filesdescription.yaml
> +    transactions to skip through inspection.
In folded scalar style, an empty line is necessary to insert a break. I think the example should be on its own line.
```suggestion
    transactions to skip through inspection.
    
```

2024-02-12 17:59 UTC, theseion commented on data/filesdescription.yaml
> +"3":
I would like this to be more specific, e.g.,:
```suggestion
versioned:
  "3":
```

2024-02-12 17:59 UTC, theseion commented on data/filesdescription.yaml
> +    involved with malicious activity, either on our local site or globally. |
```suggestion
    involved with malicious activity, either on our local site or globally.
```

2024-02-12 19:01 UTC, fzipi commented on layouts/shortcodes/describe-rules.html
> +{{- $files := merge $.Site.Data.filesdescription.common (index $.Site.Data.filesdescription $crsversion)}}
```suggestion
{{- $files := merge $.Site.Data.filesdescription.common (index $.Site.Data.filesdescription.versioned $crsversion)}}
```

2024-02-12 19:04 UTC, fzipi commented on data/filesdescription.yaml
> +  RESPONSE-955-WEB-SHELLS.conf: TODO
```suggestion
  "4":
    REQUEST-905-COMMON-EXCEPTIONS.conf: TODO
    RESPONSE-955-WEB-SHELLS.conf: TODO
```

2024-02-12 19:04 UTC, fzipi commented on data/filesdescription.yaml
> +    of Service) attacks against your server.
```suggestion
  "3":
    REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf: TODO
    REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf: TODO
    REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf: TODO
    REQUEST-903.9004-DOKUWIKI-EXCLUSION-RULES.conf: TODO
    REQUEST-903.9005-CPANEL-EXCLUSION-RULES.conf: TODO
    REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf: TODO
    REQUEST-910-IP-REPUTATION.conf: >
      These rules deal with detecting traffic from IPs that have   previously been involved with malicious activity, either on our local site or globally.
    REQUEST-912-DOS-PROTECTION.conf: >
      The rules in this file will attempt to detect some level 7 DoS (Denial of Service) attacks against your server.
```

2024-02-12 19:46 UTC, theseion commented on layouts/shortcodes/describe-rules.html
> +{{- $files := merge $.Site.Data.filesdescription.common (index $.Site.Data.filesdescription $crsversion)}}
Yes, indeed.

2024-02-13 06:53 UTC, theseion approved these changes

2024-02-13 06:53 UTC, theseion commented
LGTM.

2024-02-13 13:25 UTC, merged

2024-02-13 13:33 UTC, dune73 commented
Agreed